POST http://localhost:8800/api/hotels HTTP/1.1
content-type: application/json

{
    "name": "hotel honolulu",
    "desc": "hotel the best on the world",

    "type": "hotel ",
    "city": "holland",
    "address": "5 bus bis dubou",
    "distance": "500",
    "rating": "4",
    "cheapestPrice": "500",
   


    "title": "hotel soft"

   
}